"""add finding known_ransomware

Revision ID: 964300d982ea
Revises: a9391291eb37
Create Date: 2026-09-24 19:40:58.568329
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = '964300d982ea'
down_revision: str | None = 'a9391291eb37'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'finding',
        sa.Column('known_ransomware', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding', 'known_ransomware')
    # ### end Alembic commands ###
