"""initial schema

Revision ID: a9391291eb37
Revises: 
Create Date: 2026-09-24 17:03:54.965899
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = 'a9391291eb37'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_value', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_source'), 'apikey', ['source'], unique=True)
    op.create_table('scan',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sa.Enum('PASSIVE', 'ACTIVE', name='scanmode'), nullable=False),
    sa.Column('planner_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extractor_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'STOPPED', name='scanstatus'), nullable=False),
    sa.Column('budget_max_steps', sa.Integer(), nullable=False),
    sa.Column('budget_max_minutes', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_domain'), 'scan', ['domain'], unique=False)
    op.create_table('setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('asset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('DOMAIN', 'SUBDOMAIN', 'IP', 'SERVICE', 'URL', 'EMAIL_CONFIG', name='assettype'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_metadata', sa.JSON(), nullable=True),
    sa.Column('first_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_scan_id'), 'asset', ['scan_id'], unique=False)
    op.create_index(op.f('ix_asset_value'), 'asset', ['value'], unique=False)
    op.create_table('toolcall',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'ERROR', 'REJECTED', name='toolcallstatus'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toolcall_scan_id'), 'toolcall', ['scan_id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='findingseverity'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remediation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kev', sa.Boolean(), nullable=False),
    sa.Column('epss', sa.Float(), nullable=True),
    sa.Column('cve', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_scan_id'), 'finding', ['scan_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('finding_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_output', sa.LargeBinary(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_asset_id'), 'evidence', ['asset_id'], unique=False)
    op.create_index(op.f('ix_evidence_finding_id'), 'evidence', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_finding_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_asset_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_finding_scan_id'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_toolcall_scan_id'), table_name='toolcall')
    op.drop_table('toolcall')
    op.drop_index(op.f('ix_asset_value'), table_name='asset')
    op.drop_index(op.f('ix_asset_scan_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_table('setting')
    op.drop_index(op.f('ix_scan_domain'), table_name='scan')
    op.drop_table('scan')
    op.drop_index(op.f('ix_apikey_source'), table_name='apikey')
    op.drop_table('apikey')
    # ### end Alembic commands ###
